defaults: &defaults
  #working_directory: ./circleci
  docker:
      - image: circleci/node:12.6.0

version: 2.1

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    environment:
      CI: false
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  check:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run check
  test-jest:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            npm test -- --coverage --watchAll=false
            ./cc-test-reporter after-build --exit-code $?
  deploy-gh-pages:
    <<: *defaults
    environment:
      CI: false
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:  
          name: Configure Git credentials
          command: |
            git config user.email "steve@sr.digital"
            git config user.name "Steve Robertson"
      - run: 
          name: Deploy to GitHub Pages
          command: npm run deploy
workflows:
  version: 2

  build:
    jobs:
      - prepare:
          filters:
            branches:
              ignore: gh-pages
      - check:
          requires:
            - prepare
      - build:
          requires:
            - check
      - test-jest:
          requires:
            - build
      - deploy-gh-pages:
          filters:
            branches:
              only: main
          requires:
            - test-jest