# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.0

jobs:
  build:
    filters:
      branches:
        ignore: 
          - main
          - gh-pages

    environment:
      CC_TEST_REPORTER_ID: "6dbf1df2457214d9a18c1b22ea31538192eec2582b734807fca4da426358c0d2"

    docker:
      # specify the version you desire here
      - image: circleci/node:12.6.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Check file formatting
          command: npm run check

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
  test:
    environment:
      CC_TEST_REPORTER_ID: "6dbf1df2457214d9a18c1b22ea31538192eec2582b734807fca4da426358c0d2"
      
    docker:
      - image: circleci/node:12.6.0

      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            npm test -- --coverage --watchAll=false
            ./cc-test-reporter after-build --exit-code $?
  build-deploy:
    filters:
      branches:
        only:
          - main

    environment:
      CC_TEST_REPORTER_ID: "6dbf1df2457214d9a18c1b22ea31538192eec2582b734807fca4da426358c0d2"

    docker:
      # specify the version you desire here
      - image: circleci/node:12.6.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Check file formatting
          command: npm run check

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            npm test -- --coverage --watchAll=false
            ./cc-test-reporter after-build --exit-code $?

      - run:
          name: Deploy to GitHub Pages
          command: npm run deploy